version: "3"

services:

  app:
    build:
      context: .
    container_name: app
    tty: true
    networks:
      - app-network
    volumes:
      - .:/usr/app
    ports:
      - "8000:8000"
      - "7000:7000"
    depends_on:
      - db

  db:
    image: postgres:15.4
    container_name: db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
